//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbHostelManagementSystemEntities : DbContext
    {
        public DbHostelManagementSystemEntities()
            : base("name=DbHostelManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<LeaveAndBooked> LeaveAndBookeds { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Hostel> Hostels { get; set; }
        public virtual DbSet<RoombookingInfo> RoombookingInfoes { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<LogingException> LogingExceptions { get; set; }
    }
}
