//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int paymentsId { get; set; }
        public Nullable<int> hostelId { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Type { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> roomId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> IsCreatedBy { get; set; }
        public Nullable<System.DateTime> IsCreatedOn { get; set; }
        public Nullable<int> IsUpdateBy { get; set; }
        public Nullable<System.DateTime> IsUpdateOn { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual Hostel Hostel { get; set; }
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
