//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.LeaveAndBookeds = new HashSet<LeaveAndBooked>();
            this.RoombookingInfoes = new HashSet<RoombookingInfo>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int roomId { get; set; }
        public int Number { get; set; }
        public Nullable<int> Size { get; set; }
        public double Rent { get; set; }
        public string IsRoomAvailable { get; set; }
        public Nullable<int> IsCreatedBy { get; set; }
        public Nullable<System.DateTime> IsCreatedOn { get; set; }
        public Nullable<int> IsUpdateBy { get; set; }
        public Nullable<System.DateTime> IsUpdateOn { get; set; }
        public Nullable<int> hostelId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> NoBooking { get; set; }
        public Nullable<int> NoSeatAvailable { get; set; }
    
        public virtual Hostel Hostel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveAndBooked> LeaveAndBookeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoombookingInfo> RoombookingInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
